version: 2
updates:
  - package-ecosystem: "npm"
    versioning-strategy: "increase"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    directory: "/"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 14
    labels:
      - "dependencies"
    groups:
      npm-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 14
    labels:
      - "dependencies"
    groups:
      github-actions-dependencies:
        patterns:
          - "*"
